build_config = {
    'files': {
        'generic': [
            #'__init__.py',
            'configuration_dlg.ui',
            'configuration.py',
            'generate_calc_input_dlg.ui',
            'generate_calc_input.py',
            'imaer_plugin_base.py',
            'LICENSE',
            'relate_calc_results_dlg.ui',
            'relate_calc_results.py',
            'time_varying_profile_dlg.ui',
            'time_varying_profile.py',
            'version.py',
            'algs/__init__.py',
            'algs/provider.py',
            'algs/relate_difference.py',
            'algs/relate_maximum.py',
            'algs/relate_sum.py',
            'algs/relate.py',
            'config/__init__.py',
            'config/emissions.py',
            'gpkg/__init__.py',
            'gpkg/field_factory.py',
            'gpkg/imaer_gpkg.py',
            'imaer6/__init__.py',
            'imaer6/buildings.py',
            'imaer6/calc_point.py',
            'imaer6/emission_source.py',
            'imaer6/generic.py',
            'imaer6/geometry.py',
            'imaer6/gml.py',
            'imaer6/identifier.py',
            'imaer6/imaer_document.py',
            'imaer6/metadata.py',
            'imaer6/receptors.py',
            'imaer6/roads_adms.py', # tbr
            'imaer6/roads.py',
            'imaer6/time_varying_profile.py',
            'img/icon_configuration.svg',
            'img/icon_documentation.svg',
            'img/icon_generate_calc_input.svg',
            'img/icon_import_calc_result.svg',
            'img/icon_relate_calc_results.svg',
            'styles/__init__.py',
            'styles/classifications.py',
            'styles/style_factory.py',
            'tasks/__init__.py',
            'tasks/import_calc_result.py',
        ],
        'nl': [
            '__init___nl.py',
            'connect_jobs_dlg.ui',
            'connect_jobs.py',
            'connect_receptorsets_dlg.ui',
            'connect_receptorsets.py',
            'imaer_plugin_nl.py',
            'metadata_nl.txt',
            'connect/__init__.py',
            'connect/aerius_connection.py',
            'imaer6/roads_srm2.py',
            'img/icon_connect_jobs.svg',
            'img/icon_connect_receptorsets.svg',
        ],
        'uk': [
            '__init___uk.py',
            'imaer_plugin_uk.py',
            'metadata_uk.txt',
            'imaer6/roads_adms.py',
        ]
    },
    'options': {
        'nl': {
            'plugin_dir_name': 'ImaerPlugin',
            'plugin_name': 'IMAER Plugin',
        },
        'uk': {
            'plugin_dir_name': 'ApasPlugin',
            'plugin_name': 'APAS Plugin',
        },
    }
}
